# Default values for chronologist.

replicaCount: 1

image:
  repository: hypnoglow/chronologist
  # When image.tag is empty or not set, it defaults to {{ .Chart.AppVersion }}.
  # You can override this with any available tag, for example:
  # tag: 0.1.1
  tag: ""
  pullPolicy: IfNotPresent

# You probably need to adjust these resources up or down to fit your needs,
# depending on the number of existing release revisions and new release
# revisions per day.
resources:
  requests:
    cpu: 50m
    memory: 192Mi
  limits:
    cpu: 100m
    memory: 256Mi

grafana:
  addr: http://grafana.example.com
  apiKey: "" # put correct grafana api key here.

# config section defines general chronologist configuration settings.
config:
  # watchConfigMaps is used when helm is configured to store releases in
  # configmaps. This defaults to true because helm uses configmaps as a backend
  # for releases in default installation. Set this to false if you deploy helm
  # tiller with --storage=secret.
  # For more info, see: https://docs.helm.sh/using_helm/#storage-backends
  watchConfigMaps: true

  # watchSecrets is used when helm is configured to store releases in secrets.
  # This defaults to false because helm uses configmaps to store releases in default
  # installation. Set this to true if you deploy helm tiller with --storage=secret.
  # For more info, see: https://docs.helm.sh/using_helm/#storage-backends
  watchSecrets: false

  logFormat: json
  logLevel: info
  releaseRevisionMaxAge: 24h

# secretRefs define external secret resources (not included in the chart) that
# can be referenced and injected as environment variables to the application container.
# This is an array of secret names.
secretRefs: []
  # Example:
  # - chronologist-grafana-credentials

rbac:
  enabled: true
