apiVersion: v1
kind: ConfigMap
metadata:
  name: chronologist
  labels:
    app: chronologist
data:
  GRAFANA_ADDR: http://grafana.example.com
  GRAFANA_API_KEY: ABCDEF1234567890
  RELEASE_REVISION_MAX_AGE: 24h
  LOG_FORMAT: json
  LOG_LEVEL: info
