apiVersion: v1
kind: ServiceAccount
metadata:
  name: chronologist
  labels:
    app: chronologist

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: chronologist
  labels:
    app: chronologist
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: chronologist
  labels:
    app: chronologist
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: chronologist
subjects:
  - kind: ServiceAccount
    name: chronologist
    namespace: default
