apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chronologist.fullname" . }}
  labels:
    app: {{ template "chronologist.name" . }}
    chart: {{ template "chronologist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  {{- range $key, $value := .Values.config }}
  {{- $key | nindent 2}}: {{ $value | quote }}
  {{- end }}
