apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "chronologist.fullname" . }}
  labels:
    app: {{ template "chronologist.name" . }}
    chart: {{ template "chronologist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  CHRONOLOGIST_GRAFANA_ADDR: {{ .Values.grafana.addr | quote }}
  CHRONOLOGIST_LOG_FORMAT: {{ .Values.config.logFormat | quote }}
  CHRONOLOGIST_LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  CHRONOLOGIST_RELEASE_REVISION_MAX_AGE: {{ .Values.config.releaseRevisionMaxAge | quote }}
