apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "chronologist.fullname" . }}
  labels:
    app: {{ template "chronologist.name" . }}
    chart: {{ template "chronologist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "chronologist.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chronologist.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "chronologist.fullname" . }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
      containers:
        - name: {{ .Chart.Name }}
          {{- if .Values.image.tag }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          {{- else }}
          image: "{{ .Values.image.repository }}:{{ .Chart.AppVersion }}"
          {{- end }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "chronologist.fullname" . }}
            - secretRef:
                name: {{ template "chronologist.fullname" . }}
                optional: true
            {{- /*
            Secret env variables can be defined via ".Values.secretRefs" that
            represent references to secrets that do not belong to the release.
            */}}
            {{- range $secretRef := .Values.secretRefs }}
            - secretRef:
                name: {{ $secretRef }}
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
