apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ template "chronologist.fullname" . }}
  labels:
    app: {{ template "chronologist.name" . }}
    chart: {{ template "chronologist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "chronologist.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "chronologist.name" . }}
        release: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- if .Values.rbac.enabled }}
      serviceAccountName: {{ template "chronologist.fullname" . }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ template "chronologist.fullname" . }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
