{{- if .Values.secrets -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "chronologist.fullname" . }}
  labels:
    app: {{ template "chronologist.name" . }}
    chart: {{ template "chronologist.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{- $key | nindent 2}}: {{ $value | b64enc | quote }}
  {{- end }}
{{- end -}}
