# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  dep:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hypnoglow/chronologist
    steps:
      - checkout
      - run:
          command: |
            curl -sSL https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o /go/bin/dep
            chmod +x /go/bin/dep
      - run: dep ensure -v -vendor-only
      - persist_to_workspace:
          root: /go/src/github.com/hypnoglow
          paths:
            - chronologist
  test-unit:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hypnoglow/chronologist
    steps:
      - attach_workspace:
          at: /go/src/github.com/hypnoglow
      - run: go test -v $(go list ./... | grep -v e2e)
  test-build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hypnoglow/chronologist
    steps:
      - attach_workspace:
          at: /go/src/github.com/hypnoglow
      - setup_remote_docker:
          docker_layer_caching: true
      - run: docker image build -t hypnoglow/chronologist:latest .
  publish-latest:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hypnoglow/chronologist
    steps:
      - attach_workspace:
          at: /go/src/github.com/hypnoglow
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker image build -t hypnoglow/chronologist:latest --build-arg VCS_REF=$CIRCLE_SHA1 .
            docker image push hypnoglow/chronologist:latest

workflows:
  version: 2
  common-pipeline:
    jobs:
      - dep
      - test-unit:
          requires:
            - dep
      - test-build:
          requires:
            - dep
          filters:
            branches:
              ignore: master
      - publish-latest:
          requires:
            - test-build
            - test-unit
          filters:
            branches:
              only: master
